/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Controller;
import java.awt.Color;
import java.awt.Toolkit;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author andre
 */
public class MyGui extends javax.swing.JFrame {
    
    private Controller controller;

    /**
     * Creates new form MyGui
     */
    public MyGui() {
        initComponents();
        setTitle("Carrera");
        setIconImage();
        getContentPane().setBackground(Color.white);
        setLocationRelativeTo(null);
        controller = new Controller(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLine = new javax.swing.JLabel();
        lblFinish = new javax.swing.JLabel();
        lblStart = new javax.swing.JLabel();
        lblHare = new javax.swing.JLabel();
        lblTortoise = new javax.swing.JLabel();
        lblHareTitle = new javax.swing.JLabel();
        lblTortoiseTitle = new javax.swing.JLabel();
        lblHareSpeed = new javax.swing.JLabel();
        lblTortoiseSpeed = new javax.swing.JLabel();
        spnTortoiseSpeed = new javax.swing.JSpinner();
        spnHareSpeed = new javax.swing.JSpinner();
        btnTortoiseSpeed = new javax.swing.JButton();
        btnHareSpeed = new javax.swing.JButton();
        lblHareSleep = new javax.swing.JLabel();
        spnHareSleep = new javax.swing.JSpinner();
        btnHareSleep = new javax.swing.JButton();
        btnStartRace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        lblLine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/line.png"))); // NOI18N
        lblLine.setToolTipText("");

        lblFinish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/flag.png"))); // NOI18N

        lblStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/flag.png"))); // NOI18N

        lblHare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/hare.png"))); // NOI18N

        lblTortoise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/images/tortoise.png"))); // NOI18N

        lblHareTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblHareTitle.setText("Liebre");

        lblTortoiseTitle.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lblTortoiseTitle.setText("Tortuga");

        lblHareSpeed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHareSpeed.setText("Velocidad Liebre");

        lblTortoiseSpeed.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblTortoiseSpeed.setText("Velocidad Tortuga");

        spnTortoiseSpeed.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));

        spnHareSpeed.setModel(new javax.swing.SpinnerNumberModel(20, 20, 100, 1));

        btnTortoiseSpeed.setText("Dar velocidad tortuga");
        btnTortoiseSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTortoiseSpeedActionPerformed(evt);
            }
        });

        btnHareSpeed.setText("Dar velocidad Liebre");
        btnHareSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHareSpeedActionPerformed(evt);
            }
        });

        lblHareSleep.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lblHareSleep.setText("Segundos de sleep Liebre");

        spnHareSleep.setModel(new javax.swing.SpinnerNumberModel(2, 2, 10, 1));

        btnHareSleep.setText("Dar tiempo de sleep");
        btnHareSleep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHareSleepActionPerformed(evt);
            }
        });

        btnStartRace.setText("Iniciar Carrera");
        btnStartRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartRaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(lblTortoiseTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHareSleep)
                    .addComponent(spnHareSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHareSpeed)
                    .addComponent(lblHareTitle)
                    .addComponent(spnHareSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHareSpeed)
                    .addComponent(lblHareSleep))
                .addGap(148, 148, 148))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHare)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblLine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblStart, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(spnTortoiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTortoise))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTortoiseSpeed)
                                    .addComponent(btnTortoiseSpeed)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(btnStartRace)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHareTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTortoiseTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHareSpeed)
                    .addComponent(lblTortoiseSpeed))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnTortoiseSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnHareSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTortoiseSpeed)
                    .addComponent(btnHareSpeed))
                .addGap(31, 31, 31)
                .addComponent(lblHareSleep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnHareSleep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHareSleep)
                .addGap(41, 41, 41)
                .addComponent(btnStartRace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lblHare)
                .addGap(9, 9, 9)
                .addComponent(lblTortoise)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLine, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStart)
                            .addComponent(lblFinish))
                        .addGap(34, 34, 34))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHareSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHareSpeedActionPerformed
        controller.changeSpeed((int) spnHareSpeed.getValue());
    }//GEN-LAST:event_btnHareSpeedActionPerformed

    private void btnHareSleepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHareSleepActionPerformed
        controller.changeSleepTime((int) spnHareSleep.getValue());
    }//GEN-LAST:event_btnHareSleepActionPerformed

    private void btnStartRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartRaceActionPerformed
        btnStartRace.setEnabled(false);
        try {
            controller.startRace();
        } catch (InterruptedException ex) {
            Logger.getLogger(MyGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStartRaceActionPerformed

    private void btnTortoiseSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTortoiseSpeedActionPerformed
        controller.changeSpeed((int) spnTortoiseSpeed.getValue());
    }//GEN-LAST:event_btnTortoiseSpeedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHareSleep;
    private javax.swing.JButton btnHareSpeed;
    private javax.swing.JButton btnStartRace;
    private javax.swing.JButton btnTortoiseSpeed;
    private javax.swing.JLabel lblFinish;
    private javax.swing.JLabel lblHare;
    private javax.swing.JLabel lblHareSleep;
    private javax.swing.JLabel lblHareSpeed;
    private javax.swing.JLabel lblHareTitle;
    private javax.swing.JLabel lblLine;
    private javax.swing.JLabel lblStart;
    private javax.swing.JLabel lblTortoise;
    private javax.swing.JLabel lblTortoiseSpeed;
    private javax.swing.JLabel lblTortoiseTitle;
    private javax.swing.JSpinner spnHareSleep;
    private javax.swing.JSpinner spnHareSpeed;
    private javax.swing.JSpinner spnTortoiseSpeed;
    // End of variables declaration//GEN-END:variables

    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/flag.png")));
    }
    
    public void resetCompetitors(){
        int x = 29;
        int y = lblTortoise.getBounds().y;
        int width = lblTortoise.getBounds().width;
        int height = lblTortoise.getBounds().height;
        lblTortoise.setBounds(x, y, width, height);
        
        y = lblHare.getBounds().y;
        width = lblHare.getBounds().width;
        height = lblHare.getBounds().height;
        lblHare.setBounds(x, y, width, height);
        
        spnTortoiseSpeed.setValue(1);
        spnHareSpeed.setValue(20);
        spnHareSleep.setValue(2);
    }
    
     public void finishTortoise(){
        int x = 568;
        int y = lblTortoise.getBounds().y;
        int width = lblTortoise.getBounds().width;
        int height = lblTortoise.getBounds().height;
        lblTortoise.setBounds(x, y, width, height);
     }
     
     public void finishHare(){
        int x = 568;
        int y = lblHare.getBounds().y;
        int width = lblHare.getBounds().width;
        int height = lblHare.getBounds().height;
        lblHare.setBounds(x, y, width, height);
     }
    
    public void moveTortoise(int increment){
        int x = lblTortoise.getBounds().x + increment;
        int y = lblTortoise.getBounds().y;
        int width = lblTortoise.getBounds().width;
        int height = lblTortoise.getBounds().height;
        lblTortoise.setBounds(x, y, width, height);
    }
    
    public void moveHare(int increment){
        int x = lblHare.getBounds().x + increment;
        int y = lblHare.getBounds().y;
        int width = lblHare.getBounds().width;
        int height = lblHare.getBounds().height;
        lblHare.setBounds(x, y, width, height);
    }
    
    public void resetStartButton(){
        btnStartRace.setEnabled(true);
    }
}
